# Generated by Django 5.2.1 on 2025-06-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="content",
            new_name="message",
        ),
    ]
